<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Shraddha-PC" failures="1" tests="3" name="com.AssertJ.AssertDemo" time="0.648" errors="0" timestamp="2022-06-26T14:36:14 IST" skipped="0">
  <testcase classname="com.AssertJ.AssertDemo" name="numbersTest" time="0.598"/>
  <system-out/>
  <testcase classname="com.AssertJ.AssertDemo" name="stringTest" time="0.045"/>
  <system-out/>
  <testcase classname="com.AssertJ.AssertDemo" name="customClassTest" time="0.005">
    <failure message="expected [com.AssertJ.Employee@5d9526eb] but found [com.AssertJ.Employee@6d38e5b2]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [com.AssertJ.Employee@5d9526eb] but found [com.AssertJ.Employee@6d38e5b2]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at com.AssertJ.AssertDemo.customClassTest(AssertDemo.java:104)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- customClassTest -->
  <system-out/>
</testsuite> <!-- com.AssertJ.AssertDemo -->
